In [43]:
#Pandas practice
import pandas as pd

In [44]:
df = pd.read_csv('titanic.csv')
df.head(5)

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [45]:
#Do EDA on dataset
print(df.tail(5))
print("\n",df.columns)
print("\n",df.describe())

     survived  pclass  gender   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

 Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

          survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [46]:
#Passengers between age 2 to 20
age_filter = df.query("age >= 2 & age <= 20")
print(age_filter)

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
7           0       3    male   2.0      3      1  21.0750        S  NaN
9           1       2  female  14.0      1      0  30.0708        C  NaN
10          1       3  female   4.0      1      1  16.7000        S    G
12          0       3    male  20.0      0      0   8.0500        S  NaN
14          0       3  female  14.0      0      0   7.8542        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
869         1       3    male   4.0      1      1  11.1333        S  NaN
875         1       3  female  15.0      0      0   7.2250        C  NaN
876         0       3    male  20.0      0      0   9.8458        S  NaN
877         0       3    male  19.0      0      0   7.8958        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B

[165 rows x 9 columns]

In [47]:
#Passengers where gender is female and class is 1
filter1 = df.query("gender == 'female' & pclass == 1")
filter1

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
1           1       1  female  38.0      1      0   71.2833        C    C
3           1       1  female  35.0      1      0   53.1000        S    C
11          1       1  female  58.0      0      0   26.5500        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
52          1       1  female  49.0      1      0   76.7292        C    D
..        ...     ...     ...   ...    ...    ...       ...      ...  ...
856         1       1  female  45.0      1      1  164.8667        S  NaN
862         1       1  female  48.0      0      0   25.9292        S    D
871         1       1  female  47.0      1      1   52.5542        S    D
879         1       1  female  56.0      0      1   83.1583        C    C
887         1       1  female  19.0      0      0   30.0000        S    B

[94 rows x 9 columns]

In [50]:
#Average age of female and male passengers
df['age'] = df['age'].fillna(0).astype('int64')
average_age = df.groupby('gender')['age'].mean()
average_age

gender
female    23.194268
male      24.103986
Name: age, dtype: float64

In [51]:
#Count number of passengers in each class
no_of_passengers = df.groupby('pclass')['pclass'].count()
no_of_passengers

pclass
1    216
2    184
3    491
Name: pclass, dtype: int64

In [52]:
#Separate dataframes for survived and not survived passengers
df_survived = df.query('survived == 0')
print("Survived\n",df_survived)

df_notsurvived = df.query('survived == 1')
print("Not Survived\n",df_notsurvived)

Survived
      survived  pclass  gender  age  sibsp  parch     fare embarked deck
0           0       3    male   22      1      0   7.2500        S  NaN
4           0       3    male   35      0      0   8.0500        S  NaN
5           0       3    male    0      0      0   8.4583        Q  NaN
6           0       1    male   54      0      0  51.8625        S    E
7           0       3    male    2      3      1  21.0750        S  NaN
..        ...     ...     ...  ...    ...    ...      ...      ...  ...
884         0       3    male   25      0      0   7.0500        S  NaN
885         0       3  female   39      0      5  29.1250        Q  NaN
886         0       2    male   27      0      0  13.0000        S  NaN
888         0       3  female    0      1      2  23.4500        S  NaN
890         0       3    male   32      0      0   7.7500        Q  NaN

[549 rows x 9 columns]
Not Survived
      survived  pclass  gender  age  sibsp  parch     fare embarked deck
1           1       1  female   38      1      0  71.2833        C    C
2           1       3  female   26      0      0   7.9250        S  NaN
3           1       1  female   35      1      0  53.1000        S    C
8           1       3  female   27      0      2  11.1333        S  NaN
9           1       2  female   14      1      0  30.0708        C  NaN
..        ...     ...     ...  ...    ...    ...      ...      ...  ...
875         1       3  female   15      0      0   7.2250        C  NaN
879         1       1  female   56      0      1  83.1583        C    C
880         1       2  female   25      0      1  26.0000        S  NaN
887         1       1  female   19      0      0  30.0000        S    B
889         1       1    male   26      0      0  30.0000        C    C

[342 rows x 9 columns]

In [53]:
#No. of males, females in above dataframes
count_of_females_males = df_survived.groupby('gender')['gender'].count()
count_of_females_males

gender
female     81
male      468
Name: gender, dtype: int64

In [34]:
count_of_females_males = df_notsurvived.groupby('gender')['gender'].count()
count_of_females_males

gender
female    233
male      109
Name: gender, dtype: int64

In [56]:
#Sort passengers by age in descending order and display top 3
#df['age'] = df['age'].fillna(0).astype('int64')
sorted_data = df.sort_values(by = 'age', ascending = False)
sorted_data.head(3)

     survived  pclass gender  age  sibsp  parch     fare embarked deck
630         1       1   male   80      0      0  30.0000        S    A
851         0       3   male   74      0      0   7.7750        S  NaN
96          0       1   male   71      0      0  34.6542        C    A

In [41]:
df.rename(columns = {'age' : 'passenger_age', 'pclass':'class'}, inplace = True)
df.head()

   survived  class  gender  passenger_age  sibsp  parch     fare embarked deck
0         0      3    male             22      1      0   7.2500        S  NaN
1         1      1  female             38      1      0  71.2833        C    C
2         1      3  female             26      0      0   7.9250        S  NaN
3         1      1  female             35      1      0  53.1000        S    C
4         0      3    male             35      0      0   8.0500        S  NaN