In [1]:
import math
import pandas as pd
from scipy import stats
from scipy.stats import norm

8. A courier company delivers parcels in a particular area in 30 minutes. A new GPS system installed has reduced the average time to 28 minutes, when 100 trucks were studied, with a sample standard deviation of 4.2 minutes. Run a two-tailed test and a one-tailed (left-tailed) test.

In [2]:
mu0 =30
xbar = 28
n= 100
s = 4.2
alpha = 0.05

In [3]:
z_crit_two_tailed = norm.ppf(1 - alpha/2) 
z_crit_one_tailed = norm.ppf(1 - alpha) 

print(f"Two tailed (alpha = 0.05) : +-{z_crit_two_tailed:.3f}")
print(f"One tailed (alpha = 0.05) : +{z_crit_one_tailed:.3f}")

Two tailed (alpha = 0.05) : +-1.960
One tailed (alpha = 0.05) : +1.645

In [4]:
zscore = (xbar - mu0)/ (s / math.sqrt(n))
print(f"Z-score: {zscore:.3f}")

Z-score: -4.762

In [5]:
p_two_tailed = 2*( 1 - norm.cdf(abs(zscore)))
p_one_tailed = norm.cdf(zscore)

if abs(zscore) > z_crit_two_tailed:
    two_tail_decision = "Reject H0"
else:
    two_tail_decision = "Fail to Reject H0"

if zscore < z_crit_one_tailed:
    one_tail_decision = "Reject H0"
else:
    one_tail_decision = "Fail to reject H0"

print("Two tailed test")
print(f" p-value = {p_two_tailed:.4f}")
print(f" Decision: {two_tail_decision}")

print("One tailed test")
print(f" p-value = {p_one_tailed:.4f}")
print(f" Decision: {one_tail_decision}")

Two tailed test
 p-value = 0.0000
 Decision: Reject H0
One tailed test
 p-value = 0.0000
 Decision: Reject H0

9. A battery manufacturer claims that a battery which used run for 30 hours now runs for more than 30 hours due to new technology. 200 batteries were studied. Average battery time was found to be 29.5 hours with a standard deviation of 8 hours. Run a one-tailed (right-tailed) test.

In [6]:
mu1 = 30 
n1 = 200
x_bar_b = 29.5
s1 = 8
alpha = 0.05
z_crit_one_tailed = norm.ppf(1 - alpha)
z_score_batteries = (x_bar_b - mu1)/ (s1 / math.sqrt(n1))
p_one_tailed_batteries = 1 - norm.cdf(z_score_batteries)
#one tailed Decision
if z_score_batteries > z_crit_one_tailed:
    one_tail_decision = "Reject H0 (Significant improvement)"
else:
    one_tail_decision = "Fail to reject H0 (No significant improvement)"
print(f"Z-score: {z_score_batteries:.3f}")
print("One tailed test;")
print(f" p-value = {p_one_tailed_batteries:.4f}")
print(f" Decision: {one_tail_decision}")

Z-score: -0.884
One tailed test;
 p-value = 0.8116
 Decision: Fail to reject H0 (No significant improvement)

10. For the three combined Marathon datasets, extract the top 25 records with lowest finish time (Official Time column). Check the null hypothesis H0 = The average finishing time of the top 25 athletes is 130 minutes. Test it for α = 1%, 5%, and 10%.

In [7]:
#T-test
df1 = pd.read_csv('marathon_results_2015.csv')
df2 =pd.read_csv('marathon_results_2016.csv')
df3 = pd.read_csv('marathon_results_2017.csv')
df = pd.concat([df1,df2,df3])
df.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,NaN,NaN,...,1:32:00,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,NaN
1,1.0,4,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,ETH,NaN,NaN,...,1:31:59,1:47:59,2:02:42,0:04:58,-,2:09:48,2,2,2,NaN
2,2.0,8,"Chebet, Wilson",29,M,Marakwet,NaN,KEN,NaN,NaN,...,1:32:00,1:47:59,2:03:01,0:04:59,-,2:10:22,3,3,3,NaN
3,3.0,11,"Kipyego, Bernard",28,M,Eldoret,NaN,KEN,NaN,NaN,...,1:32:00,1:48:03,2:03:47,0:05:00,-,2:10:47,4,4,4,NaN
4,4.0,10,"Korir, Wesley",32,M,Kitale,NaN,KEN,NaN,NaN,...,1:32:00,1:47:59,2:03:27,0:05:00,-,2:10:49,5,5,5,NaN

In [8]:
official_time = pd.to_timedelta(df["Official Time"])
official_time = official_time.dt.total_seconds() / 60
official_time = official_time.nsmallest(25)
avg_official_time = 130    #H0

t_statistic, p_value = stats.ttest_1samp(official_time,avg_official_time)
print(f"P-value: {p_value:.2f}")

P-value: 0.00

In [9]:
alpha = 0.05
if p_value > alpha:
    print("Do not reject H0")
else:
    print("Reject H0")

Reject H0

In [10]:
alpha = 0.01
if p_value > alpha:
    print("Do not reject H0")
else:
    print("Reject H0")

Reject H0

In [11]:
alpha = 0.1
if p_value > alpha:
    print("Do not reject H0")
else:
    print("Reject H0")

Reject H0

11. For combined Marathon datasets, find if younger (age <= 30) and older (age > 30) athletes have a similar average pace.

In [12]:
df['Age'] = df['Age'].dropna()
df['Pace'] = df['Pace'].dropna()
df[['Hours','Minutes','Seconds']] =df['Pace'].str.split(':',expand =True)

df['Hours'] =df['Hours'].astype(int)
df['Minutes'] =df['Minutes'].astype(int)
df['Seconds'] =df['Seconds'].astype(int)

In [13]:
df['pace_in_seconds'] = df['Hours'] * 3600 + df['Minutes']*60 + df['Seconds']

In [14]:
younger = df[df['Age'] <= 30]['pace_in_seconds'].sample(n=50,replace=False)
older = df[df['Age'] > 30]['pace_in_seconds'].sample(n=50,replace=False)

In [16]:
t_statistic,p_value = stats.ttest_ind(younger,older)

alpha=0.05
print("P-value:",p_value)
if p_value < alpha:
    print("Do not reject H0")
else:
    print("Reject H0")

P-value: 0.8799038367278164
Reject H0

12. For StudentsPerformance.csv, using ANOVA find if there is a significant difference in Maths marks depending on the level of parental education.

In [17]:
#For StudentsPerformance.csv , using ANOVA
from scipy.stats import f_oneway
data_stud = pd.read_csv('StudentsPerformance.csv')
print(data_stud.columns)

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [18]:
print(data_stud['parental level of education'].value_counts())

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [19]:
s1 = data_stud['math score'][data_stud["parental level of education"] == "some college"]
s2 = data_stud['math score'][data_stud["parental level of education"] == "associate's degree"]
s3 = data_stud['math score'][data_stud["parental level of education"] == "high school"]
s4 = data_stud['math score'][data_stud["parental level of education"] == "some high school"]
s5 = data_stud['math score'][data_stud["parental level of education"] == "bachelor's degree"]
s6 = data_stud['math score'][data_stud["parental level of education"] == "master's degree"]

fsat, pval2 = f_oneway(s1, s2, s3, s4, s5, s6)

print(fsat)
print("P-value:",pval2)

alpha = 0.05

if pval2 < alpha :
    print("Reject H0")
else : 
    print("Do not reject H0")

6.521582600453217
P-value: 5.592272384107223e-06
Reject H0

13. Try to find if gender and smoking are related in the tips dataset.

In [21]:
from scipy.stats import chi2_contingency

df_tips = pd.read_csv('tips.csv')
df_tips.columns

#create a contigency table
c_table1 = pd.crosstab(df_tips["gender"], df_tips["smoker"])
print(c_table1)

#Perform the chi-square test
chi2_stat1, p_val1, dof1, expected1 = chi2_contingency(c_table1)
print("chi-square statistic: ", chi2_stat1)
print("p-value : ", p_val1)
print("Degree of Freedom : ", dof1)

if p_val1 < 0.05:
    print("Reject H0")
else:
    print("Do not reject H0")

smoker  No  Yes
gender
Female  54   33
Male    97   60
chi-square statistic:  0.0
p-value :  1.0
Degree of Freedom :  1
Do not reject H0

14. Consider diabetes dataset and find the relation of age with diabetes outcome.
(Hint: Group age into 3 categories: Young ≤ 30, Middle 31–50, Old > 50)

In [25]:
diabetes = pd.read_csv('diabetes.csv')
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [29]:
diabetes['AgeGroup'] = pd.cut(
    diabetes['Age'],
    bins=[0, 30, 50, diabetes['Age'].max()],
    labels=['young', 'middle', 'old'],
    right=True
)
#create a contigency table
c_table1 = pd.crosstab(diabetes['Outcome'], diabetes['AgeGroup'])
print(c_table1)

#Perform the chi-square test
chi2_stat1, p_val1, dof1, expected1 = chi2_contingency(c_table1)
print("chi-square statistic: ", chi2_stat1)
print("p-value : ", p_val1)
print("Degree of Freedom : ", dof1)

if p_val1 < 0.05:
    print("Reject H0")
else:
    print("Do not reject H0")

AgeGroup  young  middle  old
Outcome
0           327     130   43
1            90     140   38
chi-square statistic:  71.85015965734874
p-value :  2.4999773184934036e-16
Degree of Freedom :  2
Reject H0